[package]
name = "visualvault"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.38", features = ["full"] }
ratatui = "0.29.0"
crossterm = "0.29.0"
color-eyre = "0.6"
eyre = "0.6"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.9.2"
chrono = { version = "0.4", features = ["serde"] }
walkdir = "2.5"
sha2 = "0.10"
hex = "0.4"
indicatif = "0.18.0"
fuzzy-matcher = "0.3"
human_bytes = "0.4"
image = "0.25"
regex = "1.10"
dirs = "6.0.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-error = "0.2"
futures = "0.3"
async-trait = "0.1"
dashmap = "6.0"
parking_lot = "0.12"
num-format = "0.4"
num_cpus = "1.17.0"

[dev-dependencies]
tempfile = "3.10"
mockall = "0.13.1"
