[target.'cfg(all())']
rustflags = [
    "-Dwarnings",
    "-Dclippy::all",
    # "-Dclippy::pedantic",
    "-Aclippy::similar_names",
    "-Aclippy::too_many_arguments",
    "-Aclippy::type_complexity",
    "-Dclippy::needless_pass_by_value",
    "-Dclippy::redundant_allocation",
    "-Dclippy::unused_async",
    "-Dclippy::significant_drop_tightening",
    "-Dclippy::expect_used",
    "-Dclippy::unwrap_used",
    "-Dclippy::await_holding_lock",
    "-Dclippy::unnecessary_unwrap",
]
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld", "-C", "target-cpu=native"]

[target.x86_64-pc-windows-msvc]
linker = "lld-link.exe"

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld", "-C", "target-cpu=native"]

[target.x86_64-apple-darwin]
rustflags = [
    "-C",
    "link-arg=-fuse-ld=/usr/local/opt/llvm/bin/ld64.lld",
    "-C",
    "target-cpu=native",
]

[profile.release]
opt-level = 3
debug = false
lto = "fat"
codegen-units = 1
panic = "abort"
